# Generated by Django 4.2.30 on 2026-06-11 04:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(help_text='e.g., response_rate_drop, team_attrition, span_of_control', max_length=50)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('alert', 'Alert'), ('critical', 'Critical')], max_length=20)),
                ('entity_type', models.CharField(choices=[('department', 'Department'), ('team', 'Team'), ('manager', 'Manager')], max_length=20)),
                ('entity_id', models.CharField(max_length=255)),
                ('entity_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('metric_value', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(help_text='SHA-256 hash for duplicate detection', max_length=64)),
                ('file_type', models.CharField(help_text='employees, compensation_history, role_history, leave_records', max_length=30)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_imported', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('overall_score', models.DecimalField(decimal_places=2, help_text='Risk score 0–100', max_digits=5)),
                ('risk_tier', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('component_scores', models.JSONField(default=dict, help_text='Per-signal breakdown: {"tenure": 25, "compensation_gap": 40, ...}')),
                ('top_factors', models.JSONField(default=list, help_text='Top 3 contributing signals with human-readable names')),
                ('model_version', models.CharField(default='v1.0-rule', max_length=50)),
                ('model_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('scoring_method', models.CharField(choices=[('rule_based', 'Rule-Based'), ('dnn', 'Deep Neural Network')], default='rule_based', max_length=20)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleCostBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_title', models.CharField(max_length=150)),
                ('role_level', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-3', max_length=3)),
                ('median_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('p25_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('p75_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('source', models.CharField(help_text='Data source (e.g., internal_aggregation, kelly_services)', max_length=100)),
                ('effective_year', models.IntegerField()),
            ],
            options={
                'ordering': ['-effective_year', 'role_title'],
            },
        ),
    ]
