# Generated by Django 4.2.30 on 2026-06-11 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rolecostband',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_cost_bands', to='companies.company'),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='ingestionlog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_logs', to='companies.company'),
        ),
        migrations.AddField(
            model_name='ingestionlog',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalyflag',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_flags', to='companies.company'),
        ),
        migrations.AlterUniqueTogether(
            name='rolecostband',
            unique_together={('company', 'role_title', 'role_level', 'department', 'country', 'effective_year')},
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['company', 'risk_tier'], name='analytics_r_company_a0f94b_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['company', '-overall_score'], name='analytics_r_company_d9b6e2_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyflag',
            index=models.Index(fields=['company', 'is_active', '-detected_at'], name='analytics_a_company_fe36e7_idx'),
        ),
    ]
