# Generated by Django 4.2.30 on 2026-06-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskscore',
            name='scoring_method',
            field=models.CharField(choices=[('rule_based', 'Rule-Based'), ('xgboost', 'XGBoost Classifier')], default='rule_based', max_length=20),
        ),
    ]
