# Generated by Django 4.2.30 on 2026-06-12 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('companies', '0002_initial'),
        ('analytics', '0003_alter_riskscore_scoring_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalyflag',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='anomalyflag',
            name='detected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='riskscore',
            unique_together={('employee', 'company')},
        ),
    ]
