# Generated by Django 4.2.30 on 2026-06-11 04:59

import core.encryption
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=50)),
                ('full_name', core.encryption.EncryptedCharField(max_length=255)),
                ('email', core.encryption.EncryptedEmailField(blank=True, default='', max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('division', models.CharField(blank=True, default='', max_length=100)),
                ('role_title', models.CharField(max_length=150)),
                ('role_level', models.CharField(max_length=50)),
                ('hire_date', models.DateField()),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('exit_type', models.CharField(blank=True, choices=[('voluntary', 'Voluntary'), ('involuntary', 'Involuntary'), ('retirement', 'Retirement')], default='', max_length=20)),
                ('current_salary', core.encryption.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('exited', 'Exited'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.company')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employees.employee')),
            ],
            options={
                'ordering': ['full_name'],
                'unique_together': {('company', 'employee_code')},
            },
        ),
        migrations.CreateModel(
            name='RoleHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_title', models.CharField(max_length=150)),
                ('role_level', models.CharField(max_length=50)),
                ('effective_date', models.DateField()),
                ('change_type', models.CharField(choices=[('promotion', 'Promotion'), ('lateral', 'Lateral Move'), ('demotion', 'Demotion'), ('hire', 'Hire')], max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_history', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'role histories',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='ManagerChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_changes', to='employees.employee')),
                ('new_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
                ('previous_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('sick', 'Sick Leave'), ('personal', 'Personal Leave'), ('annual', 'Annual Leave'), ('unpaid', 'Unpaid Leave')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_count', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CompensationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salary', core.encryption.EncryptedDecimalField(decimal_places=2, max_digits=15)),
                ('effective_date', models.DateField()),
                ('change_reason', models.CharField(blank=True, default='', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_history', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'compensation histories',
                'ordering': ['-effective_date'],
            },
        ),
    ]
