# Generated by Django 4.2.30 on 2026-06-12 04:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFrictionAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_external_id', models.CharField(max_length=255)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('initial_scope_summary', models.TextField(blank=True, null=True)),
                ('detected_friction_type', models.CharField(help_text="'scope_creep' | 'dependency_block' | 'technical_debt' | 'ambiguity'", max_length=50)),
                ('friction_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('classification_rationale', models.TextField(blank=True, null=True)),
                ('avoidance_strategy', models.TextField(blank=True, null=True)),
                ('manager_alert_triggered', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'detected_friction_type'], name='projects_ta_company_e6c608_idx'), models.Index(fields=['employee', 'calculated_at'], name='projects_ta_employe_17302e_idx')],
                'unique_together': {('company', 'task_external_id')},
            },
        ),
        migrations.CreateModel(
            name='RawProjectSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(help_text="'jira' | 'linear'", max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(help_text='Confirmed clean metadata only')),
                ('processed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('processed', False)), fields=['company', 'processed'], name='raw_snap_unproc_idx')],
            },
        ),
    ]
