# Generated by Django 4.2.30 on 2026-06-11 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companymembership',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Link to the Employee record, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='companymembership',
            unique_together={('company', 'user')},
        ),
    ]
