# Generated by Django 4.2.30 on 2026-06-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulsesurvey',
            name='target_audience',
            field=models.CharField(default='All Employees', max_length=255),
        ),
    ]
