name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'apps/backend/**'

jobs:
  migrate-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          cd apps/backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django Database Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_ALLOWED_HOSTS: "*"
        run: |
          cd apps/backend
          python manage.py migrate --noinput
